template: |
  export const db = {
    username: '${{username}}',
    password: '${{password}}',
    host: '${{host}}',
    port: ${{port}}
  };
  export const serverPort = ${{webserverPort}};
  export const clientID = '${{clientID}}';
  export const clientSecret = '${{clientSecret}}';
  export const adminIDs = ${{adminIDs}};
path: src/config.ts
options:
  - name: Database username
    id: username
    description: The username for the database
  - name: Database password
    id: password
    description: The password for the database
  - name: Database host
    id: host
    description: The host for the database
    default: localhost
  - name: Database port
    id: port
    description: The port for the database
    default: 5432
  - name: Webserver port
    id: webserverPort
    description: The port for the webserver
    default: 8080
  - name: Application client ID
    id: clientID
    description: The client ID of the discord application
  - name: Application client secret
    id: clientSecret
    description: The client secret of the discord application
  - name: Admin IDs
    id: adminIDs
    description: The IDs to give admin permissions to
    default: "['487443883127472129']"
